name: 'git flow ci cd action'
description: 'Github action to improve git flow usage'
branding:
  icon: 'upload-cloud'
  color: 'blue'
author: 'Lucas M Cardoso'
inputs:
  master_branch:
    description: 'The master branch'
    required: true
    default: 'main'
  development_branch:
    description: 'The development branch'
    required: true
    default: 'develop'
  current_branch:
    description: 'The current branch'
    required: true
  github_token:
    description: 'The github_token token'
    required: true
  tag:
    description: 'The tag name'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.master }}
    - ${{ inputs.development }}